### ISSUE TITLE
Running `timesheet-invoice-this` gives `user-error: Can't assign to hline relative reference`

### ISSUE THREAD

**Issue by LukeSwart** [tmarble/timesheet.el#3]
After loading the example buffer via `Mx timesheet-example`, I ran `M-x timesheet-invoice-this`, and I got the error: `user-error: Can't assign to hline relative reference`.

I am getting the following output under the `Invoices` tree:

```
* Invoices
** 2015-08 Invoice #105
*** Header
:PROPERTIES:
:Invoice:  105
:BillDate: September 1, 2015
:DueDate:  September 30, 2015
:TotalHours: 0.00
:AmountDue: 0.00
:TABLE_EXPORT_FILE: /home/lucas/Timesheet/Yoyodyne/Invoices/2015-08/header.tsv
:TABLE_EXPORT_FORMAT: orgtbl-to-tsv
:PDF:      file:///home/lucas/Timesheet/Yoyodyne/Invoices/2015-08/Invoice-105.pdf
:END:
#+BEGIN:
|---------------+--------------+-------------|
| /Remit To/    | /Date/       | /Invoice #/ |
|---------------+--------------+-------------|
|               |              |             |
|               |              |             |
|               |              |             |
|---------------+--------------+-------------|
| /Bill To/     | /Terms/      | /Due Date/  |
|---------------+--------------+-------------|
|               |              |             |
|               |              |             |
|               |              |             |
|---------------+--------------+-------------|
| /Total Hours/ | /Amount Due/ | /Enclosed/  |
|---------------+--------------+-------------|
|               |              |             |
|---------------+--------------+-------------|
#+TBLFM: @2$1='(concat "$PROP_RemitTo1");::@2$2='(concat "$PROP_BillDate");::@2$3=$PROP_Invoice;N::@3$1='(concat "$PROP_RemitTo2");::@4$1='(concat "$PROP_RemitTo3");::@6$1='(concat "$PROP_BillTo1");::@6$2='(concat "$PROP_Terms");::@6$3='(concat "$PROP_DueDate");::@7$1='(concat "$PROP_BillTo2");::@8$1='(concat "$PROP_BillTo3");::@10$1='(concat "$PROP_TotalHours");%3.2f::@10$2='(timesheet-currency $PROP_AmountDue);::
#+END:
*** Detail
:PROPERTIES:
:TABLE_EXPORT_FILE: /home/lucas/Timesheet/Yoyodyne/Invoices/2015-08/detail.tsv
:TABLE_EXPORT_FORMAT: orgtbl-to-tsv
:END:
#+BEGIN:
|----------+-------------+----------+--------+-----------|
| Date     | Description | Quantity |   Rate |    Amount |
|----------+-------------+----------+--------+-----------|
|          |             |          |        |           |
|----------+-------------+----------+--------+-----------|
| /Month/  |             |     0.00 |        |      0.00 |
|----------+-------------+----------+--------+-----------|
#+TBLFM: $4=$rate;%3.2f;::$5=$3*$rate;%3.2f;::@III$3..@IIII$3=vsum(@II$3..@III$3);%3.2f;::@III$4..@IIII$4=string("/Total/");::@III$5..@IIII$5=vsum(@II$5..@III$5);%3.2f::
#+END:
```
where the cursor is taken to the second row, first column, of the second table. I suspect that table is not properly auto-filled? I also have the following in my `*Messages*` buffer:

```
Invoice 106
user-error: Can't assign to hline relative reference
```

I have the dependencies `s`, `org` and `auctex` installed, and I installed `timesheet` through MELPA. I also ran emacs with an empty init file, but I am still having this issue.

emacs-version: 24.5.1
echo $TEXINPUTS: .:/home/luke/.emacs.d/elpa/auctex-11.88.7/latex
ArchLinux OS: Linux 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux
Org-mode version 8.3.1 (8.3.1-87-g4ef2c0-elpa @ /home/luke/.emacs.d/elpa/org-20150824/)

**Comment by LukeSwart** [comment]
Another interesting note is the bill date and due date for the invoice is September, although it is currently August.

**Comment by LukeSwart** [comment]
Furthermore, I noticed that the error `` comes from the `M-x org-table-recalculate` on the "Weekly" table of hours. For example, when I run `M-x org-table-recalculate` on this table:

```
#+BEGIN: columnview :hlines 1 :id global
| /Project/      | Mon | Tue | Wed |  Thu | Fri |  Sat | Sun | /Total/ |
|----------------+-----+-----+-----+------+-----+------+-----+---------|
| AnotherProduct |     |     |     |      |     | 2.50 |     |         |
| Prototype      |     |     |     | 3.50 |     |      |     |         |
|----------------+-----+-----+-----+------+-----+------+-----+---------|
| /Daily/        |     |     |     |      |     |      |     |         |
#+TBLFM: @I$9..@II$9=vsum($2..$8);%.2f;::@II$2..@III$9='(format "%3.2f" (apply '+ '(@I..@II)));N;
```
I get the error above. Perhaps there is an issue with the table's formula?

**Comment by LukeSwart** [comment]
I submitted an SO post here: http://emacs.stackexchange.com/questions/15185/cant-assign-to-hline-relative-reference

**Comment by LukeSwart** [comment]
I submitted a PR, although there is another error involving the AmountDue having an empty string. I think the has to do with the way that the invoice's `Detail` table is parsed. The `Detail`'s "/Total/" field somehow gets parsed as an empty string, because the `amount-due` variable is set to an empty string. `amount-due` is set on the call `(setq amount-due (s-trim (substring-no-properties (caar (org-table-copy-region (point) (point))))))`, located in the `timesheet invoice` method.

**Comment by tmarble** [comment]
I had encountered this myself due to a recent org update... For reference these are the links I found

* http://thread.gmane.org/gmane.emacs.orgmode/94139
* http://thread.gmane.org/gmane.emacs.orgmode/97030
* http://thread.gmane.org/gmane.emacs.orgmode/98690

However I hadn't found the @> or @-1 tricks -- thank you! I'll work on pushing a new version to MELPA!

**Comment by LukeSwart** [comment]
BTW, in re the message `user-error: Can't assign to hline relative reference`, the org-mode folks said this:

>This is a known limitation: hline relative references are not allowed on the left hand side of a formula. The error message you get should be explicit.

So I guess we can use hline references on the right side of an org-formula's equals sign only. eh.

**Comment by tmarble** [comment]
I'd love to see the rationale for the changes, but presumably if there's some problem (ambiguity) as an _lvalue_ there is likely the same problem as an _rvalue_. I actually like the new syntax!
