### ISSUE TITLE
A little more documentation, please!

### ISSUE THREAD

**Issue by girzel** [tmarble/timesheet.el#9]
Hi, I'm trying to get a handle on timesheet.el, and have a couple of usage questions. I think having the sample file is great, to see what it's meant to look like, but I think it's lacking a bit in direction.

For instance, is the structure of the "Tasks" heading fixed? Anything other than having TODOs at level four seems to produce weird results. That would be nice to note.

The time calculations under the "Timesheet" headings: there doesn't seem to be any provision for creating these calculations automatically when running `timesheet-invoice-this`: is it expected that the user will manually run `timesheet-calc-today` at the end of each work day? That also would be nice to note.

If you do run `timesheet-invoice-this` without having created the "Timesheet" structure, the code enters an infinite loop as it tries to traverse the (non-existent) children of that heading. This would be a perfect spot to simply do the calculations automatically!

Anyway, these are some initial impressions. I would be happy to submit a PR for the documentation notes. If you agree that automatic calculation of the Timesheet is a good idea, I could probably submit a PR for that as well.

**Comment by tmarble** [comment]
@girzel thank you for your observations! Yes, the documentation could absolutely be improved! Please do submit a PR!

I debated about doing the automatic calculation as you suggest... By avoiding it then the invoicing is a little bit faster (but it may not even be noticable). Doing the calculation automatically would mean ensuring all the CLOCK lines corresponding to _month_ when calling **timesheet-invoice**  are evaluated with **timesheet-calc**. And at that point it may easiest to just eval *all* the CLOCK lines. I guess that may be better as there isn't the risk of "forgetting" to eval a relevant CLOCK line.

In any case it's not polite for the program to go into an infitite loop! Instead it should print a helpful message! Let me know which things you want to fix and I'll look at any of those things you don't want to do.

**Comment by girzel** [comment]
Cool, thanks! There goes a first PR for the docs, I hope I haven't misinterpreted anything. I removed the bit about "Start by creating an example client" since that pretty much duplicates the previous section. Let me know what you think.

**Comment by girzel** [comment]
As to the automatic calc -- if you're worried about performance we could add an option to automatically recalculate hours: then `timesheet-invoice-this` could recalculate everything if that option is `t`, or if the "Timesheet" subtree is empty. And yes, I suspect it would be simpler just to re-calc all the clock lines. What do you think?

**Comment by tmarble** [comment]
@girzel much better explanation.. thank you (merged)!

Let me know if you want to do the automatic calc of all CLOCK lines (otherwise I'll work on it).
